#!/usr/bin/env python3

import sys
if sys.prefix == sys.base_prefix:
    #print("No")
    #print(str(sys.prefix))
    #print(str(sys.base_prefix))
    sys.exit(1)
else:
    #print("Yes")
    #print(str(sys.prefix))
    #print(str(sys.base_prefix))
    sys.exit(0)
